name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  development:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: echo Run unit tests

      - name: Run integration tests
        run: echo Run integration tests

      - name: Run linter
        run: echo Run linter

      - name: Deploy to Expo development
        run: echo Building development expo app

  qa:
    runs-on: ubuntu-latest

    needs: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: echo Run unit tests

      - name: Run integration tests
        run: echo Run integration tests

      - name: Run linter
        run: echo Run linter

      - name: Deploy to Expo development
        run: echo Building qa expo app

  production:
    runs-on: ubuntu-latest

    needs: qa

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install
        
      - name: Run unit tests
        run: echo Run unit tests

      - name: Run integration tests
        run: echo Run integration tests

      - name: Run linter
        run: echo Run linter

      - name: Deploy to Expo development
        run: echo Building production expo app
