name: update
on:
    push:
      branches:
        - main

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    env:
        ANDROID_CLIENT_ID: ${{ secrets.ANDROID_CLIENT_ID }}
        REALM_APP_KEY: ${{ secrets.REALM_APP_KEY }}
        REALM_APP_KEY_PUBLIC: ${{ secrets.REALM_APP_KEY_PUBLIC }}
        EXPO_PUBLIC_REALM_APP_ID: ${{ secrets.EXPO_PUBLIC_REALM_APP_ID }}
        EXPO_PUBLIC_G_CLOUD_APP_NAME: ${{ secrets.EXPO_PUBLIC_G_CLOUD_APP_NAME }}
        EXPO_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.EXPO_PUBLIC_GOOGLE_MAPS_API_KEY }}
        EXPO_PUBLIC_PROJECT_UPDATE_URL: ${{ secrets.EXPO_PUBLIC_PROJECT_UPDATE_URL }}
        EXPO_PUBLIC_PROJECT_ID: ${{ secrets.EXPO_PUBLIC_PROJECT_ID }}
        EXPO_PUBLIC_PROXY_CLIENT_ID: ${{ secrets.EXPO_PUBLIC_PROXY_CLIENT_ID }}
        EXPO_PUBLIC_PROXY_SECRET: ${{ secrets.EXPO_PUBLIC_PROXY_SECRET }}
        EXPO_PUBLIC_IOS_CLIENT_ID: ${{ secrets.EXPO_PUBLIC_IOS_CLIENT_ID }}

    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Publish update
        run: eas update --auto -p android